[mypy]
python_version = 3.11
warn_unused_configs = True
warn_redundant_casts = True
show_error_codes = True
check_untyped_defs = True
install_types = True
non_interactive = True
explicit_package_bases = True
namespace_packages = True

# Use installed packages from the virtual environment
no_site_packages = False

files = diagrid/**/*.py

[mypy-diagrid.agent.langgraph.examples.*]
ignore_errors = True
