[mypy]
python_version = 3.11
warn_unused_configs = True
warn_redundant_casts = True
show_error_codes = True
check_untyped_defs = True
install_types = True
non_interactive = True
plugins = pydantic.mypy
explicit_package_bases = True
namespace_packages = True

files = diagrid/**/*.py