{{- if .Values.dapr.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: dapr-sentry-oidc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "catalyst-agents.labels" . | nindent 4 }}
spec:
  selector:
    app: dapr-sentry
  ports:
  - name: oidc
    port: 9080
    targetPort: 9080
    protocol: TCP
  type: ClusterIP
{{- end }}
