apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: local-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "catalyst-agents.labels" . | nindent 4 }}
spec:
  type: secretstores.kubernetes
  version: v1
  metadata: []
