---
apiVersion: v1
kind: Secret
metadata:
  name: crypto-keys
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "catalyst-agents.labels" . | nindent 4 }}
type: Opaque
stringData:
  key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAzQPXvwZ5iiE1vQCGFHxPmFI8HmcxAGTtg0XqZKEZqI6xKZ9k
    tQRhKO9Wj7fkzPHlVcvgLTBCYXYGJ7KN0qTmPQKBgQCnrD5lNLfBXGLIJR1KxqPK
    e0bJGzVdTJBvLKCM8pCHqXrCCzVdTJBvLKCM8pCHqXrCCzVdTJBvLKCM8pCH
    -----END RSA PRIVATE KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  name: crypto-rsa-pubkey
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "catalyst-agents.labels" . | nindent 4 }}
type: Opaque
stringData:
  key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzQPXvwZ5iiE1vQCGFHxP
    mFI8HmcxAGTtg0XqZKEZqI6xKZ9ktQRhKO9Wj7fkzPHlVcvgLTBCYXYGJ7KN0qTm
    -----END PUBLIC KEY-----
